### ISSUE TITLE
Font drawing will work only on black background

### ISSUE THREAD

**Issue by louisswarren** [skeeto/sort-circle#2]
The linear interpolation in `ppm_char` is backward:

https://github.com/skeeto/sort-circle/blob/1c26e8e77b13bb597ea1de1f3067d33ddde307f5/sort.c#L165-L167

This should be

                float r = a * fr + (1 - a) * br;
                float g = a * fg + (1 - a) * bg;
                float b = a * fb + (1 - a) * bb;

This doesn't cause a problem with the program as the background is black anyway.

**Comment by skeeto** [comment]
Good catch, thanks!
